// core/examples/luigi-example-angular/src/app/home/home.ts
import { Component, OnInit, signal } from '@angular/core';
import { addInitListener, addContextUpdateListener } from '@luigi-project/client';

@Component({
  selector: 'app-home',
  imports: [],
  template: `
    <div>
      <section class="fd-section">
        <div class="fd-section__header">
          <h1 class="fd-section__title">Home</h1>
        </div>
        <div class="fd-panel">
          <div class="fd-panel__body">
            {{ message() }}
          </div>
        </div>
      </section>
    </div>
  `,
  styles: ``
})
export class Home implements OnInit {
  public message = signal('');

  ngOnInit() {
    addInitListener((initialContext) => {
      this.message.set('Luigi Client initialized');
      console.log(initialContext);
    });
    addContextUpdateListener((updatedContext) => {
      this.message.set('Luigi Client updated');
      console.log(updatedContext);
    });
  }
}

// core/examples/luigi-example-svelte/src/routes/Home.svelte
<script>
  import LuigiClient from '@luigi-project/client';
  import { onMount } from 'svelte';

  let message = $state('The app loaded without Luigi');

  onMount(() => {
    LuigiClient.addInitListener(() => {
      message = 'Luigi Client initialized.';
    });
    LuigiClient.addContextUpdateListener(() => {
      message = 'Luigi Client updated.';
    });
  });
</script>

<h1>Home</h1>
<div>
  {message}
</div>
